### ISSUE TITLE
Managing updates for other applications

### ISSUE THREAD

**Issue by KillTrot** [ProgTrade/nUpdate#32] opened 2017-04-23 14:09 UTC
Hey there,

i'm currently writing something like a launcher for my other software and i want to update them with my launcher.
Therefor the actual Version cannot be the same, as the one of the launcher (which is also updated with nUpdate).
Is there a possibility to set different "assembly: nUpdateVersion"?
For example read the actual version out of a text file or something?

Greetings

**Comment by ProgTrade** [comment] 2017-04-23 20:45
Hi,

I understand what you mean. The `nUpdateVersionAttribute` is designed to be set once per assembly. Thus, you cannot specify it twice as nUpdate, additionally, wouldn't know how to differ between them. Currently, there is no other way of determining the version. Consequently, I'm afraid to say that this is not possible at the moment. nUpdate has mainly been designed to update the host application itself and not other applications in any other directory. 
Nevertheless, I've planned to implement this version management in v4 (as it has changed there as well), but there will pass a lot of time until this upgrade will be available. This feature could be achieved by adding an additional property or constructor overload that holds the version information and overrides the one handled over by the nUpdateVersionAttribute, in order to make "multiple updating" available. The source of this version wouldn't matter then, because one could load it from a file, specify it directly or read it from the depending assembly (which consists more or less the first option).
How fast do you need this feature? Is this part of any milestone you need to reach at a specific date? If so, I would implement this next weekend to make your request possible. The problem is that I'm currently very busy and stressed out by my preparations for the A-level exam. So, it depends on how fast you'd need this feature. This shouldn't be too much work, but I need to fix some other bugs in this upcoming update, too.

Best,
Dominic

**Comment by KillTrot** [comment] 2017-04-23 21:59
Thanks for your answer.

I'm writing this launcher only for me and some friends and mainly to learn the programming language. Therefore it is not a milestone i need to reach at specific date, but it is needed so i can go on with my software:)
If you're very busy, take your time doing "real life" this first with higher priority and do it, when there's time for it.
I myself unfortunately don't know how to do this (as said, i'm learning in a very early stage:P)

Many thanks for the offer!

Greets,
Cedric

**Comment by ProgTrade** [comment] 2017-04-23 22:30
Okay. I will see, if I'll find some time for it next week. If not, then surely in 3-4 weeks.
I'll do my best. ;)

Regards,
Dominic

**Comment by KillTrot** [comment] 2017-04-24 04:36
Thanks alot!

**Comment by ProgTrade** [comment] 2017-05-30 19:32
I just saw that you closed this issue althought it's still up-to-date.
I will implement this feature now to make external application controlling using nUpdate possible.

**Comment by ProgTrade** [comment] 2017-05-30 22:23
This should now be possible with version v3.0-beta8. Just have a look at the `currentVersion` parameter of the `UpdateManager` constructor. You're able to provide an `UpdateVersion` there that will hide/replace the one specified in the `nUpdateVersionAttribute`, if it's available. You can use each one of them on its own or both at the same time where the parameter has then a higher priority.
This should allow you to update external applications as well as it's no longer bound to the attribute.

**Comment by KillTrot** [comment] 2017-05-31 12:52
Thanks alot!

I'll try it out soon and give you feedback.

Greetings

**Comment by ProgTrade** [comment] 2017-06-01 08:39
Hi,

it's an optional parameter inside of the constructor. Doesn't IntelliSense show it?

Best,
Dominic

**Comment by KillTrot** [comment] 2017-06-01 13:22
IntelliSense does not show it to me, and it's not (or i just do not find it) in the dll of the update (yeah, it's here on GitHub, but i dont find it in the update...)

As said, IntelliSense does not show it, and if i write it by myself i cannot compile...

Greetings
Cedric

**Comment by ProgTrade** [comment] 2017-06-01 14:08
This seems to be an issue with regards to the version that you are using.
Is it version v3.0-beta8 or an earlier version?

Best,
Dominic

**Comment by KillTrot** [comment] 2017-06-01 14:13
According to nUpdate Administration it's Version 3.0.0.0 Beta 8.
Product Version of DLL (According to Windows Details) is V3.0 Beta 8

Therefor I dont know

**Comment by ProgTrade** [comment] 2017-06-01 14:15
Where did you download the new version?

**Comment by KillTrot** [comment] 2017-06-01 14:18
From your homepage

**Comment by ProgTrade** [comment] 2017-06-01 14:24
Just download it again from nupdate.net. I've just tested it and it works fine.
[!IntelliSense](https://www.trade-programming.de/pixelkram/uiogfgdef.png)

**Comment by KillTrot** [comment] 2017-06-01 14:29
Ah you're right, it had to do with this: 
https://github.com/ProgTrade/nUpdate/issues/29

Do you have a solution for this one?

**Comment by ProgTrade** [comment] 2017-06-01 14:37
Ah, now I understand the problem. This context is important as well. 😄 I forgot that you've overwritten the `TerminateApplication` method and therefore use an own derived class, now.
Issue #29 has been fixed in v3.0-beta8. See also issue #31. This means there is no more need for a workaround, you can just use the `UpdateManager` class as usual.

**Comment by KillTrot** [comment] 2017-06-01 14:38
Ah perfect.
Thanks alot sir:)

Have a nice day.

**Comment by ProgTrade** [comment] 2017-06-01 14:40
Glad to see the problem solved. :)
Did you manage to find the parameter and does it work as expected?

**Comment by KillTrot** [comment] 2017-06-01 14:43
I found the parameter and it worked so far:)

**Comment by ProgTrade** [comment] 2017-06-01 14:45
Okay, nice. If there is still any problem with it, just open another issue. ;)

**Closed by ProgTrade** 2017-06-01 14:45 UTC
Labels: enhancement, question
