### ISSUE TITLE
System.ArgumentException at nUpdate.UpdateInstaller.Updater.CopyDirectoryRecursively()

### ISSUE THREAD

**Issue by swASO** [ProgTrade/nUpdate#56] opened 2018-07-02 15:33 UTC
If i try to make an update with an application that run as service i get the following exception : 

```
System.ArgumentException: Der Pfad darf keine leere Zeichenfolge sein oder nur aus Leerzeichen bestehen.
   bei System.IO.Directory.CreateDirectory(String path)
   bei nUpdate.UpdateInstaller.Updater.CopyDirectoryRecursively(String sourceDirName, String destDirName) 
```

while debugging or if running as normal ui application, the exception doesnt occurs

any ideas ?

**Comment by ProgTrade** [comment] 2018-07-02 15:48
I will check that out and debug the installer with usage of an application that runs as service.

**Comment by ProgTrade** [comment] 2018-07-09 15:23
Hi,

I am still trying to figure this out. It seems there is no executable path property in a service application. But I have not yet managed to create a working service that I am able to debug. Sorry for that. I will check that out on Sunday.

Best,
Dominic

**Comment by swASO** [comment] 2018-07-12 14:25
i think i found it 
> Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory)

this is not possible as service, because a service has no desktop ;) so the return path is empty 

![image](https://user-images.githubusercontent.com/4096843/42639359-1eadac04-85f0-11e8-9a0a-ed0184a6450c.png)

![image](https://user-images.githubusercontent.com/4096843/42639382-2b835ad2-85f0-11e8-95d8-edfef470f53d.png)

**Comment by ProgTrade** [comment] 2018-07-15 09:00
Hi,

sorry for my late response. I am very busy at the moment.
Thanks for debugging. Till now, I thought, that this might be caused by the application executable path. I will see, how I can handle that.

**Comment by ProgTrade** [comment] 2018-08-01 09:15
Fixed in https://github.com/ProgTrade/nUpdate/pull/62

**Closed by ProgTrade** 2018-08-01 09:15 UTC
Labels: bug
